name: lint-on-push

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@main
      - name: setup-python
        uses: actions/setup-python@main
        with:
          python-version: 3.10.6
          cache: pip
          cache-dependency-path: requirements.txt
      - name: install-pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: pre-commit
        uses: pre-commit-ci/lite-action@v1.0.2
        if: always()
        with:
          msg: apply code formatting and linting auto-fixes
      - name: test-startup
        run: |
          export COMMANDLINE_ARGS="--debug --test"
          python launch.py
